"use client";
import { Activity,CalendarClock,ShieldAlert,UserRoundCheck,UsersRound } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { MetricCard } from "@/components/cards/MetricCard";
import { PriorityBadge,StatusBadge } from "@/components/queue/StatusBadge";
import { formatAppointmentTime,getQueueEntryTime,getRecommendedNextPatient,inferQueueType,queueTypeLabels,sortQueuePatients } from "@/lib/queueUtils";
import { useQueueStore } from "@/lib/useQueueStore";
export default function NursePage(){
 const {activePatients,callPatientToNurse,setStatus,updatePatient}=useQueueStore();
 const waiting=sortQueuePatients(activePatients.filter(p=>p.status==="waiting"||p.status==="checked-in"||p.status==="delayed"));const current=activePatients.find(p=>p.status==="nurse-check");const recommended=getRecommendedNextPatient(activePatients);
 return <AppShell title="Nurse Station" eyebrow="Single shared station for appointments and walk-ins"><div className="space-y-6">
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MetricCard title="Waiting" value={waiting.length} icon={<UsersRound/>}/><MetricCard title="Appointments" value={waiting.filter(p=>inferQueueType(p)==="appointment").length} icon={<CalendarClock/>}/><MetricCard title="Walk-ins" value={waiting.filter(p=>inferQueueType(p)==="walk-in").length} icon={<UserRoundCheck/>}/><MetricCard title="Urgent" value={waiting.filter(p=>p.priority==="urgent").length} icon={<ShieldAlert/>} tone="red"/></div>
  <section className="grid gap-5 xl:grid-cols-2">
   <div className="glass-panel rounded-2xl p-5"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-clinic-teal">Now at Nurse Station</p>{current?<div className="mt-4 rounded-2xl border border-clinic-line bg-white p-6"><div className="flex flex-wrap items-center gap-3"><span className="rounded-xl bg-clinic-teal px-4 py-3 text-2xl font-black text-white">{current.code}</span><StatusBadge status={current.status}/><PriorityBadge priority={current.priority}/></div><p className="mt-5 text-xl font-bold text-navy-900">{current.name}</p><p className="mt-2 text-sm text-clinic-muted">{queueTypeLabels[inferQueueType(current)]}{inferQueueType(current)==="appointment"?` · ${formatAppointmentTime(current)}`:""}</p><button onClick={()=>setStatus(current.code,"completed")} className="mt-5 rounded-full bg-green-50 px-4 py-2 text-sm font-bold text-clinic-success">Complete</button></div>:<div className="mt-4 rounded-2xl border border-dashed border-clinic-line bg-white p-8 text-center text-clinic-muted">No patient currently called.</div>}</div>
   <div className="glass-panel rounded-2xl p-5"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-clinic-teal">CareFlow recommendation</p><h2 className="mt-1 text-2xl font-bold text-navy-900">Who should be called next?</h2>{recommended?<div className="mt-4 rounded-2xl bg-clinic-blue p-6"><p className="text-4xl font-black text-navy-900">{recommended.code}</p><p className="mt-2 font-bold">{recommended.name}</p><p className="mt-1 text-sm text-clinic-muted">{queueTypeLabels[inferQueueType(recommended)]}{inferQueueType(recommended)==="appointment"?` · ${formatAppointmentTime(recommended)}`:" · arrival order"}</p><button onClick={()=>callPatientToNurse(recommended.code)} className="mt-4 inline-flex items-center gap-2 rounded-2xl bg-clinic-teal px-5 py-3 font-bold text-white"><Activity className="h-5 w-5"/>Call {recommended.code}</button></div>:<div className="mt-4 rounded-2xl border border-dashed border-clinic-line bg-white p-8 text-center text-clinic-muted">No eligible patient right now.</div>}<p className="mt-4 text-sm leading-6 text-clinic-muted">Appointments become eligible 10 minutes before their scheduled time. Walk-ins stay first-come-first-served. Urgent cases can be moved ahead by staff.</p></div>
  </section>
  <section className="glass-panel rounded-2xl p-5"><h2 className="text-2xl font-bold text-navy-900">Shared queue</h2><div className="mt-5 grid gap-4">{waiting.map((p,i)=><div key={p.id} className={`rounded-2xl border bg-white p-5 ${recommended?.id===p.id?"border-clinic-teal":"border-clinic-line"}`}><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-3"><span className="rounded-xl bg-clinic-teal px-3 py-2 font-black text-white">{p.code}</span><span className="text-xs font-bold text-clinic-muted">#{i+1}</span><p className="font-bold text-navy-900">{p.name}</p><PriorityBadge priority={p.priority}/></div><p className="mt-3 text-sm text-clinic-muted">{queueTypeLabels[inferQueueType(p)]}{inferQueueType(p)==="appointment"?` · ${formatAppointmentTime(p)}${getQueueEntryTime(p)>Date.now()?" · checked in early":""}`:""}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>callPatientToNurse(p.code)} className="rounded-full bg-clinic-teal px-4 py-2 text-xs font-bold text-white">Call</button><button onClick={()=>updatePatient(p.code,{priority:"urgent"})} className="rounded-full bg-[#FFF1F1] px-4 py-2 text-xs font-bold text-clinic-error">Urgent</button></div></div></div>)}{waiting.length===0&&<div className="rounded-2xl border border-dashed border-clinic-line bg-white p-10 text-center text-clinic-muted">No patients waiting.</div>}</div></section>
 </div></AppShell>
}
